name: Build and Publish

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check unused code
        run: npm run knip

      - name: Run typecheck
        run: npm run typecheck

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "NPM_TOKEN length: ${#NPM_TOKEN}"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          cat .npmrc
          npm whoami
          npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
